logo: images/favicon.ico
footer_bg: images/flutter-bottom.svg

hero:
  title: Flutter 1.2 已经发布
  desc: Flutter 是 Google 用以帮助开发者在 iOS 和 Android 两个平台开发高质量原生 UI 的移动 SDK。Flutter 兼容现有的代码，免费并且开源，在全球开发者中广泛被使用。
hero_docs:
  - text: 1.2 更新内容
    url: https://flutter-io.cn/posts/launching-flutter-12-at-mobile-world.html
    clss: color-red
    color: 
  - text: 官方英文文档
    url: https://flutter.io/docs
    clss: color-white
    color: rgb(244, 67, 54);

google_analytics_id: UA-135552747-1

# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: Flutter 社区中文资源
    url: https://flutter-io.cn/
  - name: Flutter Gallery
    url: https://www.coolapk.com/apk/io.flutter.demo.gallery
  - name: Flutter Codelabs
    url: https://codelabs.flutter-io.cn/
  - name: Flutter 官方网站
    url: https://flutter.dev/
  - name: DartPad
    url: https://dartpad.cn/

# navigation menu
menu:
  - name: 首页
    slug: home
    url: /
  - name: 归档
    slug: archives
    url: /archives
  - name: 订阅
    slug: subscribe
    url: /subscribe
  - name: 关于
    slug: about
    url: /about
  # - name: 视频资源
  #   slug: videos
  #   url: https://flutter-io.cn/#videos
  # - name: 插件推荐
  #   slug: plugins
  #   url: https://flutter-io.cn/#plugins
  # - name: CodeLabs
  #   slug: codelabs
  #   url: https://flutter-io.cn/#codelabs
  # - name: 中文社区
  #   slug: community
  #   url: https://flutter-io.cn/#community
  # - name: 使用镜像
  #   slug: cn-mirror
  #   url: https://flutter-io.cn/#cn-mirror

# widgets
widgets: 
  - about
  - categories
  - tagcloud
  - links

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/cfug
- slug: twitter
  url: https://twitter.com/FlutterChina
- slug: sina-weibo
  url: https://weibo.com/flutterio
- slug: rss
	url: /atom.xml

auto_excerpt:
  enable: true
  lines: 5

beian:
  - type: communication
    value: 豫ICP备18021312号-1
    url: http://www.miitbeian.gov.cn/
  - type: police
    value: 豫公网安备41010702002474号
    url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41010702002474